packaging_format = 2

id = "spftoolbox"
name = "SPFtoolbox"
description.en = "Look up DNS records such as SPF, MX, Whois"
description.fr = "Recherchez des enregistrements DNS tels que SPF, MX, Whois"

version = "2025.08.22~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "http://spftoolbox.com/"
demo = "http://spftoolbox.com/"
code = "https://github.com/charlesabarnes/SPFtoolbox"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/spftoolbox"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/charlesabarnes/SPFtoolbox/archive/f6b5ee88989518062dcc289c06244bb7f77f32bc.tar.gz"
        sha256 = "d5dc0cc26185f1433a5e7d139d0a3a23109cabc3fbf80f3afc54d2c5d6bc4e47"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "whois, php8.3-fpm"
