packaging_format = 2

id = "spftoolbox"
name = "SPFtoolbox"
description.en = "Look up DNS records such as SPF, MX, Whois"
description.fr = "Recherchez des enregistrements DNS tels que SPF, MX, Whois"

version = "2025.05.09~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "http://spftoolbox.com/"
demo = "http://spftoolbox.com/"
code = "https://github.com/charlesabarnes/SPFtoolbox"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/spftoolbox"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/charlesabarnes/SPFtoolbox/archive/32917e8dcfa13e2f1ba43faa63cae9bd8016bbbe.tar.gz"
        sha256 = "c0b783ef5403094f0ef39d4a0c54ea1a44f7a296990bfd8b9deccdb007cc9028"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "whois, php8.3-fpm"
